parameters:
    login_url: https://auth.w3.org/
    login_redirect_param: url
    logout_url: https://auth.w3.org/loggedin
    frontend_base_url: https://www.w3.org/
services:
    W3C\WebsiteTemplatesBundle\Service\Utils:
        public: false
    w3c_website_templates_bundle.twig_extension:
        class: W3C\WebsiteTemplatesBundle\Twig\TwigExtension
        arguments:
            $intl: '@twig.extension.intl'
            $translator: '@translator'
            $twig: '@twig'
            $utils: '@W3C\WebsiteTemplatesBundle\Service\Utils'
            $requestStack: '@request_stack'
            $loginUrlInfo:
                login_url: '%login_url%'
                login_redirect_param: '%login_redirect_param%'
                logout_url: '%logout_url%'
        tags:
            - { name: twig.extension }
    W3C\WebsiteTemplatesBundle\Form\Extension\ChoiceTypeExtension:
        tags:
            - { name: form.type_extension }
    W3C\WebsiteTemplatesBundle\EventSubscriber\FlashMessageSubscriber:
        arguments:
            $requestStack: '@request_stack'
            $translator: '@translator'
        tags:
            - { name: kernel.event_subscriber }
    W3C\WebsiteTemplatesBundle\Extensions\Twig\GetFromFrontendExtension:
        arguments:
            $baseUrl: '%env(default:frontend_base_url:FRONTEND_BASE_URL)%'
            $client: '@http_client'
            $cachePath: '%kernel.project_dir%/var/storage/menus/'
        tags:
            - { name: twig.extension }
